### PR TITLE
Update adk_whitepaper.tex

### PR DESCRIPTION
**Pull request by Ashman01**
Here is page 2, I have stopped at line #216 (to await your answer to the comments below).  I think I will only submit one page at time for you to look at otherwise the comments would be a lot to deal with, I will keep working ahead on an offline copy while you are reviewing this page.

Some comments:

#187 to #189 appears to be discussing potential options for providing anonymity to ADK, would this be more appropriate in the section above (under the heading "Strong Anonymity")? - I propose to move this section to the "Strong Anonymity" section so that under "Related Works" we talk about Monero and Bytecoin and then go straight to talking about Iota. - Please let me know if you agree and I will combine and re-write appropriately.

I wonder if we should mention that the code was originally forked from Iota - if we do not mention it people may accuse us of trying to hide it.  I have mentioned it in line #193 but it can be removed if required.

Lines #179 and #191 are intended to be subheadings - can you please make them bold in the final version

We need a source for line #203

Lines #203 to #215  can you please look at this extra closely to make sure it is technically accurate.

### CODE REVIEW

**Comment by keep-looking** [comment]
Thank you for your work!

> #187 to #189 appears to be discussing potential options for providing anonymity to ADK, would this be more appropriate in the section above (under the heading "Strong Anonymity")? - I propose to move this section to the "Strong Anonymity" section

I think the section still should be there because I intend to explain why we don't use
coinjoin which is "related works".

I will add "CoinJoin" with bold font before the paragraph.

> I wonder if we should mention that the code was originally forked from Iota

I'm thiking we will complete rewite codes and don't use IOTA codes and  ideas anymore for 2nd step.
So I guess we don't need to mention about IOTA code.


> Lines #179 and #191 are intended to be subheadings 

will do.

> We need a source for line #203
> Lines #203 to #215 can you please look at this extra closely to make sure it is technically accurate.

will check later.

BTW, my text editor claims that we should not use ``` '***' ``` and suggests to use ``` `***' ``` instead.
(e.g.  quotes symbole after back quotes symbol). You seem to use former one. 
Which should we use?

**Comment by Ashman01** [comment]
> Your suggestion makes sense. It would be great if you would rewrite the section.

Ok, I will fix that up when I submit the next page.

> I'm thiking we will complete rewite codes and don't use IOTA codes and ideas anymore for 2nd step.
So I guess we don't need to mention about IOTA code.

 I would probably tend to keep it, because we do mention that IOTA uses ternary and we have chosen to use binary. I have currently written it as follows:

> IOTA is a DAG based, fee-less, IoT focussed cryptocurrency from which the Aidos Kuneen source code was originally based. 

However, I think I will replace "originally" with "initially" to make it more apparent that we don't use their code anymore.

> will make it be subsections of "related work"

Ok

> will check later.

Ok

> BTW, my text editor claims that we should not use '***' and suggests to use `***' instead.
(e.g. quotes symbole after back quotes symbol). You seem to use former one.
Which should we use?

I've honestly never seen the second one used before. Wikipedia suggests that it not used much in modern English [https://en.wikipedia.org/wiki/Grave_accent#English]

One quick question from the next part I'm working on, you have 

> To generate a public key, one gets 67 number of 32 bytes (256 bits) random binary data as his private key

Are you meaning that the public key is made up of a total of 67 characters, each of 32 bytes in size?

**Comment by keep-looking** [comment]
after typeset

'zk-SNARKs' will be 
screenshot at 2017-12-30 17-46-28

and `zk-SNARKs' will be 
screenshot at 2017-12-30 17-46-50

so it seems we should use ``` `***' ``` (for latex) ?

**Comment by Ashman01** [comment]
Ah ok, yep if that is how latex interprets it then I will use the second format from now on.

**Comment by keep-looking** [comment]
> However, I think I will replace "originally" with "initially" to make it more apparent that we don't use their code anymore.

ok.

Once we finished 2nd step, we can review the sentence.

> Are you meaning that the public key is made up of a total of 67 characters, each of 32 bytes in size?
 
yes
one gets a private key, and he makes a public key from the private key.
both the private key and  the public key are  made up of a total of 67 characters, each of 32 bytes in size

**Comment by Ashman01** [comment]
I did try to pull the tex file into a latex editor so I could tweak formatting too (though I haven't used latex in years) but I couldn't get it to work so I gave up.

**Comment by keep-looking** [comment]
> We need a source for line #203

I thought I saw the source before, but now i don't find it.
So I guess I need to change the sentence.
will try later

**Comment by keep-looking** [comment]
> I did try to pull the tex file into a latex editor so I could tweak formatting too (though I haven't used latex in years) but I couldn't get it to work so I gave up.

ok, no problem. I can check

**Comment by Ashman01** [comment]
> Once we finished 2nd step, we can review the sentence.

No problem, I will change it to "initially" and then just leave it, it can be changed at a later date if required.

> yes
> one gets a private key, and he makes a public key from the private key.
> both the private key and the public key are made up of a total of 67 characters, each of 32 bytes in size

Ok, I thought that was what you meant but just wanted to check.

> I thought I saw the source before, but now i don't find it. So I guess I need to change the sentence.
will try later

It's not in their whitepaper or anything is it?

**Comment by keep-looking** [comment]
>  will try later

fixed and pushed.
removed first sentence in paragraph.

**Pull request merged**
