### PR TITLE
Update adk_whitepaper.tex

### PR DESCRIPTION
**Pull request by Ashman01**
Hello, I have edited the first page, up to line #156. 

Please review to make sure it is still technically accurate.

I do have a couple of questions: 

Line #70: Is coPow completely new and unique to Aidos Kuneen? Or is it built on an existing technology?

Line #149 and #151: Line #149 says that the transaction is added to iMesh immediately, Line #151 says that the bigger iMesh gets the faster the transaction confirms - these two lines seem to contradict each other.

Please let me know if you are happy with my work and would like me to keep going with the rest of the document.

### CODE REVIEW

**Comment by keep-looking** [comment]
Thank you for your great help!

> Line #70: Is coPow completely new and unique to Aidos Kuneen? Or is it built on an existing technology?

Yes, i guess it's a new concept, which  is inspired by raft cnsensus protocol and mining pool.

>Line #149 and #151: Line #149 says that the transaction is added to iMesh immediately, Line #151 says that the bigger iMesh gets the faster the transaction confirms - these two lines seem to contradict each other.

"tx is added to iMesh" does not equal to "tx is confirmed".
Imagine Bitcoin, where a tx is stored into a block after 10 minutes, but you would not think it is confirmed if you want 5 confirmations.



>Please let me know if you are happy with my work and would like me to keep going with the rest of the document.

I really appreciate your awsome work !
I would be happy if you will keep going your work.

**Comment by Ashman01** [comment]
> Yes, i guess it's a new concept, which is inspired by raft cnsensus protocol and mining pool.

Ok that's great, I was just wanting to know if I could refer to coPow as being "unique" or "new" and wanted to make sure that was actually correct.

> "tx is added to iMesh" does not equal to "tx is confirmed".
Imagine Bitcoin, where a tx is stored into a block after 10 minutes, but you would not think it is confirmed if you want 5 confirmations.

No problem, that makes perfect sense, it reads correctly then so there are no issues.

> I really appreciate your awsome work !
I would be happy if you will keep going your work.

No problem, I will keep doing a a few pages a day until I get through it all. Now that the introduction is out of the way the rest should hopefully be a bit quicker.

**Comment by keep-looking** [comment]
In the whipaper:
"This in turn leads to a scal-
ability problem when many transactions are broadcast
simultaneously"

"broadcast" should be "broadcasted", right?

**Comment by Ashman01** [comment]
It can be either, in British English (I am Australian) we use broadcast as the past tense. If you prefer broadcasted you can change it back, but to me broadcast reads correctly.

[https://en.wiktionary.org/wiki/broadcasted](url)

**Comment by keep-looking** [comment]
fixed some (maybe) typo. please let me know if it doesn't make sense.


maycontrol up to 50\% 
->
may control up to 50\% 

transaction is stored into iMesh immediately. Hence there is no need to wait for one's own transaction to be confirmed. 
->
transaction is stored into iMesh immediately. Hence there is no need to wait for one's own transaction to be stored.


there is no limitation to the size or number of transactions tha can be stored at atime. 
->
there is no limitation to the size or number of transactions tha can be stored at a time.

**Comment by Ashman01** [comment]
Yep, all good catches. That last one still needs a "t" added to the end of "tha" - it should read "there is no limitation to the size or number of transactions **that** can be stored at a time."

There will probably be quite a few little bits and pieces like that so definitely read through it all. Also keep an eye out,  I am quite prone to typing "trasnaction" instead of "transaction" and have caught and fixed that myself quite a few times already.

**Comment by keep-looking** [comment]
i can run a spell checker once you have finished.

> The last one still needs a "t" added to the end of "tha" - it should read "there is no limitation to the size or number of transactions that can be stored at a tim

oh :) . will fix

**Comment by Ashman01** [comment]
Just doing some more editing, can you explain this part please:

> The key size of Ring-LWE and Lattice based signature are around a few Kilo Bytes. This means, for example, that we 
must copy and paste a long string on the website to let people know his address. This is not practical for normal use of cryptocurrency.
One of hash-based signatures, e.g. SPHINCS, by which we can use the public key many times, also suffice from the public key size (about 1 KByte)
 
When you talk about copying the long string on the website are you talking about needing to manually copy and paste the signature each time we want to use the address? And with SPHINCS or XMSS we can instead just use the public key many times? 

Sorry, I don't really understand the tech in detail so I'm not quite sure what this part is trying to say.

**Comment by keep-looking** [comment]
>When you talk about copying the long string on the website are you talking about needing to manually copy and paste the signature each time we want to use the address? 

for example, of course it's easy  to copy and paste the public key to ads or business card , but  it's too long to read, so it's hard to let peple know it.

normally if the public key is long, the signautre is short, and vice versa.
public key is one which people see directly. on the other hand signautres are handled only by PCs, so they don't see signatures directly.
total size(signature+public key) is most important, because data size(a transaction size) depends on the total size.
but if total size is nearly equal, i'm thiking it's more importatnt to shoten the public key than signature.

the public key size of XMSS is just 32 bytes, so it's easy to handle for people.

>>by which we can use the public key many times

i guess the sentence  is not needed. It may confuse readers because it has nothing 
to do with the context.

I really appreciate your great efforts to understand  my bad engrish :(

**Comment by Ashman01** [comment]
Ok thanks, that clears it up a bit. I think I understand what you were trying to convey.

I didn't get much done yesterday so I will do a bunch more today and send it through all at once.

**Pull request merged**
